### ISSUE TITLE
can you update it to support the latest ijkplayer framework updates?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [shinrenpan/SRPPlayerViewController#1]
can you update it to support the latest ijkplayer framework updates?

**Comment by shinrenpan** [comment]
Busy at working, I will upgrade ijkplayer this week...... maybe :cry:

**Comment by Sebacho-Barajas** [comment]
okay thanks!

**Comment by shinrenpan** [comment]
Upgrade ijkplayer to k0.7.4

**Comment by Sebacho-Barajas** [comment]
@shinrenpan  thanks!
