### ISSUE TITLE
how to build framework?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [shinrenpan/SRPPlayerViewController#4]
can you teach me how to build ijkplayer framework? i want to build it with the latest release and more codec formats! 
thanks!

**Comment by shinrenpan** [comment]
### Step1
Follow the ijkplayer [tutorial](https://github.com/Bilibili/ijkplayer#build-ios) to setup ffmpeg

### Step2
Follow this [post](https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9#.vkjviqmzf) to setup bitcode.

### Step3
Download this [script](https://github.com/shinrenpan/SRPPlayerViewController/blob/master/build.sh#L11) into `ios/IJKMediaPlayer/` folder.  
Modify `FRAMEWORK_NAME="SRPPlayerViewController"` to `FRAMEWORK_NAME="IJKMediaFramework"`  
Run script, the IJKMediaFramework.framework will generate on your desktop.

**Comment by Sebacho-Barajas** [comment]
thanks you @shinrenpan !
by the way can I ask for a feature request? 
can you add repeat/loop mode to repeat videos?

**Comment by shinrenpan** [comment]
@Sebacho-Barajas I think you can use protocol to implement this feature
for example:

```objc
- (void)playerController:(SRPPlayerViewController *)playerController finishReason:(IJKMPMovieFinishReason)reason
{
    if(reason == IJKMPMovieFinishReasonPlaybackEnded)
    {
        playerController.currentPlaybackTime = 0.0;
        [playerController play];
    }
}

**Comment by Sebacho-Barajas** [comment]
@shinrenpan do I need to build framework in desktop? I did all the steps but Xcode keeps running the script for ever and i won't get the framework

**Comment by Sebacho-Barajas** [comment]
fixed by changing my run scheme to "release"

**Comment by Sebacho-Barajas** [comment]
@shinrenpan the idea you gave me for repeat mode does not work with remote files.
